--REGIONES
ALTER TABLE REGIONES ALTER COLUMN code NVARCHAR(255) NOT NULL
GO
ALTER TABLE REGIONES
ADD CONSTRAINT PK_REGIONES PRIMARY KEY (code);
GO
--PROVINCIAS
ALTER TABLE PROVINCIAS ALTER COLUMN code NVARCHAR(255) NOT NULL
ALTER TABLE PROVINCIAS ALTER COLUMN REGIONCODE NVARCHAR(255) NOT NULL
GO
ALTER TABLE PROVINCIAS
ADD FOREIGN KEY (REGIONCODE) REFERENCES REGIONES(code);

ALTER TABLE PROVINCIAS
ADD CONSTRAINT PK_PROVINCIAS PRIMARY KEY (REGIONCODE,code);

-- MUNICIPIOS
ALTER TABLE MUNICIPIOS ALTER COLUMN code NVARCHAR(255) NOT NULL
ALTER TABLE MUNICIPIOS ALTER COLUMN REGIONCODE NVARCHAR(255) NOT NULL
ALTER TABLE MUNICIPIOS ALTER COLUMN provinceCode NVARCHAR(255) NOT NULL
GO
ALTER TABLE MUNICIPIOS
ADD CONSTRAINT PK_MUNICIPIOS PRIMARY KEY (regionCode,provinceCode, code);

ALTER TABLE MUNICIPIOS
ADD FOREIGN KEY (regionCode,provinceCode) REFERENCES PROVINCIAS(REGIONCODE, code);

-- DISTRITOS
ALTER TABLE DISTRITOS ALTER COLUMN code NVARCHAR(255) NOT NULL
ALTER TABLE DISTRITOS ALTER COLUMN REGIONCODE NVARCHAR(255) NOT NULL
ALTER TABLE DISTRITOS ALTER COLUMN provinceCode NVARCHAR(255) NOT NULL
ALTER TABLE DISTRITOS ALTER COLUMN municipalityCode NVARCHAR(255) NOT NULL
GO
ALTER TABLE DISTRITOS
ADD FOREIGN KEY (regionCode,provinceCode,municipalityCode) REFERENCES MUNICIPIOS(regionCode,provinceCode, code);

ALTER TABLE DISTRITOS
ADD CONSTRAINT PK_DISTRITOS PRIMARY KEY (regionCode,provinceCode,municipalityCode,code);

-- SECTORES
ALTER TABLE SECTORES ALTER COLUMN code NVARCHAR(255) NOT NULL
ALTER TABLE SECTORES ALTER COLUMN REGIONCODE NVARCHAR(255) NOT NULL
ALTER TABLE SECTORES ALTER COLUMN provinceCode NVARCHAR(255) NOT NULL
ALTER TABLE SECTORES ALTER COLUMN municipalityCode NVARCHAR(255) NOT NULL
ALTER TABLE SECTORES ALTER COLUMN districtCode NVARCHAR(255) NOT NULL
GO
ALTER TABLE SECTORES
ADD FOREIGN KEY (regionCode,provinceCode,municipalityCode,districtCode) REFERENCES DISTRITOS(regionCode,provinceCode,municipalityCode,code);

ALTER TABLE SECTORES
ADD CONSTRAINT PK_SECTORES PRIMARY KEY (regionCode,provinceCode,municipalityCode,districtCode,code);

-- VECINDARIOS
ALTER TABLE VECINDARIOS ALTER COLUMN code NVARCHAR(255) NOT NULL
ALTER TABLE VECINDARIOS ALTER COLUMN REGIONCODE NVARCHAR(255) NOT NULL
ALTER TABLE VECINDARIOS ALTER COLUMN provinceCode NVARCHAR(255) NOT NULL
ALTER TABLE VECINDARIOS ALTER COLUMN municipalityCode NVARCHAR(255) NOT NULL
ALTER TABLE VECINDARIOS ALTER COLUMN districtCode NVARCHAR(255) NOT NULL
ALTER TABLE VECINDARIOS ALTER COLUMN sectionCode NVARCHAR(255) NOT NULL
GO

ALTER TABLE VECINDARIOS
ADD FOREIGN KEY (regionCode,provinceCode,municipalityCode,districtCode,sectionCode) REFERENCES SECTORES(regionCode,provinceCode,municipalityCode,districtCode,code);

ALTER TABLE VECINDARIOS
ADD CONSTRAINT PK_VECINDARIOS PRIMARY KEY (regionCode,provinceCode,municipalityCode,districtCode,sectionCode,code);

-- SUB_VECINDARIOS
ALTER TABLE SUB_VECINDARIOS ALTER COLUMN code NVARCHAR(255) NOT NULL
ALTER TABLE SUB_VECINDARIOS ALTER COLUMN REGIONCODE NVARCHAR(255) NOT NULL
ALTER TABLE SUB_VECINDARIOS ALTER COLUMN provinceCode NVARCHAR(255) NOT NULL
ALTER TABLE SUB_VECINDARIOS ALTER COLUMN municipalityCode NVARCHAR(255) NOT NULL
ALTER TABLE SUB_VECINDARIOS ALTER COLUMN districtCode NVARCHAR(255) NOT NULL
ALTER TABLE SUB_VECINDARIOS ALTER COLUMN sectionCode NVARCHAR(255) NOT NULL
ALTER TABLE SUB_VECINDARIOS ALTER COLUMN neighborhoodCode NVARCHAR(255) NOT NULL
GO
ALTER TABLE SUB_VECINDARIOS
ADD FOREIGN KEY (regionCode,provinceCode,municipalityCode,districtCode,sectionCode,neighborhoodCode) REFERENCES VECINDARIOS(regionCode,provinceCode,municipalityCode,districtCode,sectionCode,code);

ALTER TABLE SUB_VECINDARIOS
ADD CONSTRAINT PK_VECINDARIOS PRIMARY KEY (regionCode,provinceCode,municipalityCode,districtCode,sectionCode,neighborhoodCode,code);